### ISSUE TITLE
ProducerAPI get_product() is not working

### ISSUE THREAD

**Issue by SvenLehmann** [hpi-epic/pricewars-merchant#1]
When you call ProducerAPI.get_product(product_uid) the following error is thrown:
```TypeError: type object argument after ** must be a mapping, not list```

This method assumes that the response from the Producer is a JSON containing a dictionary. However, the Producer returns a JSON Array.

To me it would be more intuitive to receive a single Product object, but the API definition states that this route returns a JSON Array containing a single element. 

I leave it to you to decide on which side you want to fix this.

**Comment by Bouncner** [comment]
Who is `you`?

**Comment by SvenLehmann** [comment]
```You``` as in someone who works on this application. 
I can create a Merge Request to fix this, when we have decided on which side it is going to be fixed. The second ```you```was not intended to shirk work :)

**Comment by Bouncner** [comment]
I would propose we stay with the API definition for now. This means we need to adopt the producer?
