### ISSUE TITLE
Use logging module

### ISSUE THREAD

**Issue by CarstenWalther** [hpi-epic/pricewars-merchant#3]
Use the logging module instead of the handcrafted logging which is implemented  in the API classes.
This should allow us to change the logging behavior globally.

**Comment by Bouncner** [comment]
Reason for close?

**Comment by CarstenWalther** [comment]
This was an old issue. The merchant already uses the python `logging module`

**Comment by Bouncner** [comment]
Please include the PR number when closing  issues.

**Comment by CarstenWalther** [comment]
Actually this was done in the most recent pull request #4
